In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [48]:
from sklearn.preprocessing import LabelEncoder

In [163]:
df = pd.read_csv('/content/drive/MyDrive/Synoris Training/Day1_training/Fraud Detection Dataset.csv')

In [164]:
df.head()

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,NaN,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0

In [165]:
df.shape

(51000, 12)

In [166]:
df.describe()

,User_ID,Transaction_Amount,Time_of_Transaction,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Fraudulent
count,51000.000000,48480.000000,48448.000000,51000.000000,51000.000000,51000.000000,51000.000000
mean,3005.110176,2996.249784,11.488400,1.995725,60.033902,7.495588,0.049216
std,1153.121107,5043.932555,6.922954,1.415150,34.384131,4.020080,0.216320
min,1000.000000,5.030000,0.000000,0.000000,1.000000,1.000000,0.000000
25%,2007.000000,1270.552500,5.000000,1.000000,30.000000,4.000000,0.000000
50%,2996.000000,2524.100000,12.000000,2.000000,60.000000,7.000000,0.000000
75%,4006.000000,3787.240000,17.000000,3.000000,90.000000,11.000000,0.000000
max,4999.000000,49997.800000,23.000000,4.000000,119.000000,14.000000,1.000000

In [167]:
df.columns

Index(['Transaction_ID', 'User_ID', 'Transaction_Amount', 'Transaction_Type',
       'Time_of_Transaction', 'Device_Used', 'Location',
       'Previous_Fraudulent_Transactions', 'Account_Age',
       'Number_of_Transactions_Last_24H', 'Payment_Method', 'Fraudulent'],
      dtype='object')

In [168]:
''.join(df.columns)

'Transaction_IDUser_IDTransaction_AmountTransaction_TypeTime_of_TransactionDevice_UsedLocationPrevious_Fraudulent_TransactionsAccount_AgeNumber_of_Transactions_Last_24HPayment_MethodFraudulent'

In [169]:
df['Fraudulent'].value_counts()

Fraudulent
0    48490
1     2510
Name: count, dtype: int64

In [170]:
df.corr(numeric_only=True)

,User_ID,Transaction_Amount,Time_of_Transaction,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Fraudulent
User_ID,1.000000,0.001191,0.001941,0.002567,0.001749,-0.005847,0.008046
Transaction_Amount,0.001191,1.000000,-0.007015,-0.001151,0.003203,-0.004538,0.005507
Time_of_Transaction,0.001941,-0.007015,1.000000,-0.003411,-0.003055,-0.009274,0.007035
Previous_Fraudulent_Transactions,0.002567,-0.001151,-0.003411,1.000000,0.000956,-0.000303,0.001136
Account_Age,0.001749,0.003203,-0.003055,0.000956,1.000000,0.004215,0.006203
Number_of_Transactions_Last_24H,-0.005847,-0.004538,-0.009274,-0.000303,0.004215,1.000000,-0.003877
Fraudulent,0.008046,0.005507,0.007035,0.001136,0.006203,-0.003877,1.000000

In [142]:
df.isnull().sum()

Transaction_ID                         0
User_ID                                0
Transaction_Amount                  2520
Transaction_Type                       0
Time_of_Transaction                 2552
Device_Used                         2473
Location                            2547
Previous_Fraudulent_Transactions       0
Account_Age                            0
Number_of_Transactions_Last_24H        0
Payment_Method                      2469
Fraudulent                             0
dtype: int64

In [175]:
df = df.drop('Transaction_ID',axis =1)

In [176]:
for col in df.columns:
  if df[col].dtype =='object':
    df[col] =  df[col].fillna('Unknown')
  else:
    df[col] = df[col].fillna(df[col].mean())

In [177]:
df.isnull().sum()

User_ID                             0
Transaction_Amount                  0
Transaction_Type                    0
Time_of_Transaction                 0
Device_Used                         0
Location                            0
Previous_Fraudulent_Transactions    0
Account_Age                         0
Number_of_Transactions_Last_24H     0
Payment_Method                      0
Fraudulent                          0
dtype: int64

In [178]:
df.nunique()

User_ID                              4000
Transaction_Amount                  44822
Transaction_Type                        5
Time_of_Transaction                    25
Device_Used                             5
Location                                9
Previous_Fraudulent_Transactions        5
Account_Age                           119
Number_of_Transactions_Last_24H        14
Payment_Method                          6
Fraudulent                              2
dtype: int64

## Apply encoding for necessary columns

In [179]:
df_encod = df.copy()

In [180]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [181]:
le = LabelEncoder()

In [182]:

Categorical_features = ['Transaction_Type','Device_Used','Location','Payment_Method']

In [183]:
for col in Categorical_features:
  df_encod[col] = le.fit_transform(df_encod[col])

df_encod = pd.get_dummies(df_encod,columns=Categorical_features)

In [184]:

df_encod.head()

,User_ID,Transaction_Amount,Time_of_Transaction,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Fraudulent,Transaction_Type_0,Transaction_Type_1,Transaction_Type_2,...,Location_5,Location_6,Location_7,Location_8,Payment_Method_0,Payment_Method_1,Payment_Method_2,Payment_Method_3,Payment_Method_4,Payment_Method_5
0,4174,1292.76,16.0000,0,119,13,0,True,False,False,...,False,True,False,False,False,True,False,False,False,False
1,4507,1554.58,13.0000,4,79,3,0,True,False,False,...,True,False,False,False,True,False,False,False,False,False
2,1860,2395.02,11.4884,3,115,9,0,True,False,False,...,False,False,False,True,False,False,False,False,False,True
3,2294,100.10,15.0000,4,3,4,0,False,False,True,...,False,False,False,False,False,False,False,False,True,False
4,2130,1490.50,19.0000,2,57,7,0,False,False,False,...,False,True,False,False,True,False,False,False,False,False

In [185]:
df_encod.tail()

,User_ID,Transaction_Amount,Time_of_Transaction,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Fraudulent,Transaction_Type_0,Transaction_Type_1,Transaction_Type_2,...,Location_5,Location_6,Location_7,Location_8,Payment_Method_0,Payment_Method_1,Payment_Method_2,Payment_Method_3,Payment_Method_4,Payment_Method_5
50995,2339,3112.51,15.0,0,7,8,0,False,False,True,...,True,False,False,False,False,True,False,False,False,False
50996,2152,2897.15,3.0,1,75,11,1,False,False,False,...,False,False,False,False,False,False,False,True,False,False
50997,3345,2204.43,18.0,3,73,5,0,False,False,False,...,False,True,False,False,True,False,False,False,False,False
50998,1518,4787.17,19.0,2,108,14,0,False,False,False,...,True,False,False,False,False,False,False,True,False,False
50999,2315,814.72,3.0,0,50,10,0,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [186]:
df_encod.shape

(51000, 32)

## splite data

In [187]:
df_encod.head()

,User_ID,Transaction_Amount,Time_of_Transaction,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Fraudulent,Transaction_Type_0,Transaction_Type_1,Transaction_Type_2,...,Location_5,Location_6,Location_7,Location_8,Payment_Method_0,Payment_Method_1,Payment_Method_2,Payment_Method_3,Payment_Method_4,Payment_Method_5
0,4174,1292.76,16.0000,0,119,13,0,True,False,False,...,False,True,False,False,False,True,False,False,False,False
1,4507,1554.58,13.0000,4,79,3,0,True,False,False,...,True,False,False,False,True,False,False,False,False,False
2,1860,2395.02,11.4884,3,115,9,0,True,False,False,...,False,False,False,True,False,False,False,False,False,True
3,2294,100.10,15.0000,4,3,4,0,False,False,True,...,False,False,False,False,False,False,False,False,True,False
4,2130,1490.50,19.0000,2,57,7,0,False,False,False,...,False,True,False,False,True,False,False,False,False,False

In [188]:
X = df_encod.drop('Fraudulent',axis=1)
y = df_encod['Fraudulent']

In [189]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## apply standarization

In [190]:
scaler = StandardScaler()

In [191]:
X_train.head()

,User_ID,Transaction_Amount,Time_of_Transaction,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Transaction_Type_0,Transaction_Type_1,Transaction_Type_2,Transaction_Type_3,...,Location_5,Location_6,Location_7,Location_8,Payment_Method_0,Payment_Method_1,Payment_Method_2,Payment_Method_3,Payment_Method_4,Payment_Method_5
36563,1692,3063.37,15.0,0,67,9,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
8326,1946,1935.63,6.0,0,33,1,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
11100,3870,3807.93,13.0,2,21,2,False,False,True,False,...,False,True,False,False,False,True,False,False,False,False
20260,3125,2692.52,2.0,2,97,12,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
33279,1588,3484.60,9.0,0,93,3,False,False,False,True,...,True,False,False,False,True,False,False,False,False,False

In [192]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape:", X_test_scaled.shape)

X_train_scaled shape: (40800, 31)
X_test_scaled shape: (10200, 31)

In [195]:
clf = LogisticRegression(random_state=42)

In [196]:
clf.fit(X_train_scaled,y_train)

LogisticRegression(random_state=42)

In [200]:
y_pred_Regression = clf.predict(X_test_scaled)

In [198]:
Tree_classifier = DecisionTreeClassifier(random_state=42)

In [199]:
Tree_classifier.fit(X_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [201]:
y_pred_tree = Tree_classifier.predict(X_test_scaled)

In [203]:
Logistic_score = accuracy_score(y_test,y_pred_Regression)
Logistic_score

0.9498039215686275

In [204]:
Tree_score = accuracy_score(y_test,y_pred_tree)
Tree_score

0.9002941176470588

In [205]:
print("Confusion Matrix for Logistic Regression:")
print(confusion_matrix(y_test, y_pred_Regression))

print("\nConfusion Matrix for Decision Tree:")
print(confusion_matrix(y_test, y_pred_tree))

Confusion Matrix for Logistic Regression:
[[9688    0]
 [ 512    0]]

Confusion Matrix for Decision Tree:
[[9118  570]
 [ 447   65]]